version: "3.2"
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.alpine-x64-selfcontained
    ports:
      - "80:80"
  web2:
    build:
        context: .
        dockerfile: Dockerfile.debian-x64-selfcontained
    ports:
      - "81:80"
