FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /app

# copy csproj and restore as distinct layers
RUN dotnet new mvc -o dotnetapp
WORKDIR /app/dotnetapp
RUN dotnet restore

# copy and build app and libraries
#WORKDIR /app/
#COPY dotnetapp/. ./dotnetapp/
#WORKDIR /app/dotnetapp
RUN dotnet publish -c Release -r linux-x64 -o out --self-contained true /p:PublishTrimmed=true


FROM mcr.microsoft.com/dotnet/core/runtime-deps:3.0-buster-slim AS runtime
WORKDIR /app
COPY --from=build /app/dotnetapp/out ./
ENTRYPOINT ["./dotnetapp"]
