version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:latest"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            mynetwork:
                aliases:
                    - db1.internal.prod.example.com
networks:
  mynetwork:
    driver: bridge          
